// <auto-generated />
using System;
using JwtIssueExample.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JwtIssueExample.Migrations
{
    [DbContext(typeof(JwtExampleContext))]
    [Migration("20200821213427_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JwtIssueExample.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54d39f1a-ef2d-4816-b2e8-90991f548bf0"),
                            Password = "RegularPassword",
                            Type = 1,
                            UserName = "Regular"
                        },
                        new
                        {
                            Id = new Guid("36f72591-1d95-4e4f-877c-261d3386df94"),
                            Password = "AdminPassword",
                            Type = 2,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("fb270c9a-9479-4bd0-9c86-589f3fa84527"),
                            Password = "SuperPassword",
                            Type = 3,
                            UserName = "Super"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
